### PR TITLE
fix: pwa router corruption when switching accounts in certain way

### LINKED ISSUE #1697: Navigation issue with PWA
**Describe the bug**
Ionic Router weirdness

**To Reproduce**

1. Load app
2. Click on post in feed
3. Go to profile page
4. Switch profile
5. Go back to posts tab
6. Go back
7. BOOM!

**Expected behavior**

no boom

**Screenshots**

💥

**Smartphone (please complete the following information):**

PWA only, native app unaffected

**Additional context**

None

### PR DESCRIPTION
**Pull request by aeharding**
Resolves #1697

### CODE REVIEW

File: src/routes/common/ActorRedirect.tsx [hunk 1]
```diff
@@ -13,28 +15,48 @@ export default function ActorRedirect({ children }: React.PropsWithChildren) {
...
     (state) => state.auth.connectedInstance,
   );
   const location = useLocation();
   const ionViewIsVisible = useIonViewIsVisible();
+  const router = useOptimizedIonRouter();
 
-  if (!ionViewIsVisible) return children;
-  if (!connectedInstance || !actor) return children;
-  if (connectedInstance === actor) return children;
+  const fixedForPathname = useRef("");
```
Comment (aeharding) [inline src/routes/common/ActorRedirect.tsx:25]: May not be needed w/ react compiler
